deployment:
  tasks:
    - export NODE_ENV=production
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
    - export DEPLOYPATH=/home/nextend1/public_html/
    - /bin/cp -r build/ $DEPLOYPATH